// <auto-generated>
// This file was generated by MauiStyleGenerator from RapidXaml.CodeGen.Maui
// learn more at https://github.com/mrlacey/XamlStyleTypes
// </auto-generated>


namespace VDCA
{
    public static partial class AppColors
    { 
        public const string PrimaryYellow = "PrimaryYellow";
        public const string PrimaryWhite = "PrimaryWhite";
        public const string PrimaryBlack = "PrimaryBlack";
        public const string PrimaryText = "PrimaryText";
        public const string PrimaryTextColor = "PrimaryTextColor";
        public const string PrimaryBackground = "PrimaryBackground";
        public const string PrimaryButtonBackground = "PrimaryButtonBackground";
        public const string PrimaryButtonText = "PrimaryButtonText";
        public const string PrimaryCardQBackground = "PrimaryCardQBackground";
        public const string PrimaryCardABackground = "PrimaryCardABackground";
        public const string PrimaryCardQBackgroundDark = "PrimaryCardQBackgroundDark";
        public const string PrimaryCardABackgroundDark = "PrimaryCardABackgroundDark";
        public const string PrimaryInformationBackground = "PrimaryInformationBackground";
        public const string PrimaryPass = "PrimaryPass";
        public const string PrimaryLowPass = "PrimaryLowPass";
        public const string PrimaryFail = "PrimaryFail";
        public const string PrimaryCardProgressbarLeft = "PrimaryCardProgressbarLeft";
        public const string PrimaryCardProgressText = "PrimaryCardProgressText";
        public const string PrimaryListDescriptionText = "PrimaryListDescriptionText";
        public const string PrimaryCardIcons = "PrimaryCardIcons";
        public const string PrimaryCardIconsSelected = "PrimaryCardIconsSelected";
        public const string PrimaryAllListSelected = "PrimaryAllListSelected";
        public const string PrimaryGreyedText = "PrimaryGreyedText";
        public const string PrimaryCardTextDark = "PrimaryCardTextDark";
        public const string PrimaryLabelOptions = "PrimaryLabelOptions";
        public const string PrimaryOptionsButtonBackground = "PrimaryOptionsButtonBackground";
        public const string PrimaryBackgroundBuzy = "PrimaryBackgroundBuzy";
        public const string PrimaryIconLightMode = "PrimaryIconLightMode";
        public const string PrimaryMenuBackground = "PrimaryMenuBackground";
    }

}

