// <auto-generated>
// This file was generated by MauiStyleGenerator from RapidXaml.CodeGen.Maui
// learn more at https://github.com/mrlacey/XamlStyleTypes
// </auto-generated>


namespace VDCA
{
    // No suitable content was found to generate classes for.
}

